base_config: ./config/fusedRGB.yaml
results_csv: experiment_results.csv
experiments:
- name: RGB/severity/unet/resnet18
  dataset_name: RGB_severity
  overrides:
    arch: unet
    encoder: resnet18
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_rgb
    train_images_dir: train/data
    train_masks_dir: train/label_severity
    val_images_dir: val/data
    val_masks_dir: train/label_severity
    test_images_dir: test/data
    test_masks_dir: train/label_severity
    in_channels: 3
    experiment_name: RGB/severity/unet/resnet18
- name: RGB/severity/segformer/mit_b0
  dataset_name: RGB_severity
  overrides:
    arch: segformer
    encoder: mit_b0
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_rgb
    train_images_dir: train/data
    train_masks_dir: train/label_severity
    val_images_dir: val/data
    val_masks_dir: train/label_severity
    test_images_dir: test/data
    test_masks_dir: train/label_severity
    in_channels: 3
    experiment_name: RGB/severity/segformer/mit_b0
- name: RGB/none_severity/unet/resnet18
  dataset_name: RGB_none_severity
  overrides:
    arch: unet
    encoder: resnet18
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_rgb
    train_images_dir: train/data
    train_masks_dir: train/label_none_severity
    val_images_dir: val/data
    val_masks_dir: train/label_none_severity
    test_images_dir: test/data
    test_masks_dir: train/label_none_severity
    in_channels: 3
    experiment_name: RGB/none_severity/unet/resnet18
- name: RGB/none_severity/segformer/mit_b0
  dataset_name: RGB_none_severity
  overrides:
    arch: segformer
    encoder: mit_b0
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_rgb
    train_images_dir: train/data
    train_masks_dir: train/label_none_severity
    val_images_dir: val/data
    val_masks_dir: train/label_none_severity
    test_images_dir: test/data
    test_masks_dir: train/label_none_severity
    in_channels: 3
    experiment_name: RGB/none_severity/segformer/mit_b0
- name: ALL/severity/unet/resnet18
  dataset_name: ALL_severity
  overrides:
    arch: unet
    encoder: resnet18
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_data
    train_images_dir: train/data
    train_masks_dir: train/label_severity
    val_images_dir: val/data
    val_masks_dir: train/label_severity
    test_images_dir: test/data
    test_masks_dir: train/label_severity
    in_channels: 55
    experiment_name: ALL/severity/unet/resnet18
- name: ALL/severity/segformer/mit_b0
  dataset_name: ALL_severity
  overrides:
    arch: segformer
    encoder: mit_b0
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_data
    train_images_dir: train/data
    train_masks_dir: train/label_severity
    val_images_dir: val/data
    val_masks_dir: train/label_severity
    test_images_dir: test/data
    test_masks_dir: train/label_severity
    in_channels: 55
    experiment_name: ALL/severity/segformer/mit_b0
- name: ALL/none_severity/unet/resnet18
  dataset_name: ALL_none_severity
  overrides:
    arch: unet
    encoder: resnet18
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_data
    train_images_dir: train/data
    train_masks_dir: train/label_none_severity
    val_images_dir: val/data
    val_masks_dir: train/label_none_severity
    test_images_dir: test/data
    test_masks_dir: train/label_none_severity
    in_channels: 55
    experiment_name: ALL/none_severity/unet/resnet18
- name: ALL/none_severity/segformer/mit_b0
  dataset_name: ALL_none_severity
  overrides:
    arch: segformer
    encoder: mit_b0
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_data
    train_images_dir: train/data
    train_masks_dir: train/label_none_severity
    val_images_dir: val/data
    val_masks_dir: train/label_none_severity
    test_images_dir: test/data
    test_masks_dir: train/label_none_severity
    in_channels: 55
    experiment_name: ALL/none_severity/segformer/mit_b0
- name: CHM/severity/unet/resnet18
  dataset_name: CHM_severity
  overrides:
    arch: unet
    encoder: resnet18
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_chm
    train_images_dir: train/data
    train_masks_dir: train/label_severity
    val_images_dir: val/data
    val_masks_dir: train/label_severity
    test_images_dir: test/data
    test_masks_dir: train/label_severity
    in_channels: 1
    experiment_name: CHM/severity/unet/resnet18
- name: CHM/severity/segformer/mit_b0
  dataset_name: CHM_severity
  overrides:
    arch: segformer
    encoder: mit_b0
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_chm
    train_images_dir: train/data
    train_masks_dir: train/label_severity
    val_images_dir: val/data
    val_masks_dir: train/label_severity
    test_images_dir: test/data
    test_masks_dir: train/label_severity
    in_channels: 1
    experiment_name: CHM/severity/segformer/mit_b0
- name: CHM/none_severity/unet/resnet18
  dataset_name: CHM_none_severity
  overrides:
    arch: unet
    encoder: resnet18
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_chm
    train_images_dir: train/data
    train_masks_dir: train/label_none_severity
    val_images_dir: val/data
    val_masks_dir: train/label_none_severity
    test_images_dir: test/data
    test_masks_dir: train/label_none_severity
    in_channels: 1
    experiment_name: CHM/none_severity/unet/resnet18
- name: CHM/none_severity/segformer/mit_b0
  dataset_name: CHM_none_severity
  overrides:
    arch: segformer
    encoder: mit_b0
    dataset_dir: /root/code/Rice_Segment/DatasetProcessing/synthetic_chm
    train_images_dir: train/data
    train_masks_dir: train/label_none_severity
    val_images_dir: val/data
    val_masks_dir: train/label_none_severity
    test_images_dir: test/data
    test_masks_dir: train/label_none_severity
    in_channels: 1
    experiment_name: CHM/none_severity/segformer/mit_b0
